export * from './alumno.repository';
export * from './asistencia.repository';
export * from './detalle-asistencia.repository';
export * from './detalle-matricula.repository';
export * from './docente.repository';
export * from './horario.repository';
export * from './materia.repository';
export * from './matricula.repository';
export * from './seccion.repository';
