export * from './alumno.model';
export * from './asistencia.model';
export * from './detalle-asistencia.model';
export * from './matricula.model';
export * from './seccion.model';
export * from './docente.model';
export * from './detalle-matricula.model';
export * from './materia.model';
export * from './horario.model';
